port = 25565 # set this to the port you want to scan
iplist_file = "./ips.txt" # file with your list of ips to scan (seperated by a new line or \n)
timeout_ms = 500 # time in ms until it times out

mongo_hostname = "db" # hostname of the mongodb instance (leave this like this if using docker-compose)
mongo_root_username = "root"
mongo_root_passwd = "password" # format this accordingly

mongo_newuser_passwd = "password" # no need to format accordingly, password for a *new, created* user