port = 25565 # set this to the port you want to scan
iplist_file = "./ips.txt" # file with your list of ips to scan (seperated by a new line or \n)
output_file = "./output.json" # output file (json). it will get cleared before start
clear_output = true # clear output file before writing
timeout_ms = 500 # time in ms until it times out